/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jnlsahsxqiufusfamccz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpubHNhaHN4cWl1ZnVzZmFtY2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzExMTksImV4cCI6MjA4ODI0NzExOX0.piJcDQtUusFsG0nm-PO26AaatESdYGaVh0-X-D6dujY"