/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "olieryxyhakumgyohlrr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9saWVyeXh5aGFrdW1neW9obHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3Njk4MzUsImV4cCI6MjA4NjM0NTgzNX0.CFx--o13bJaMowjWDaBvkEqO3mZPEl2AGDytZeujSzM"