import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Login
    'login.title': 'PROMIX',
    'login.subtitle': 'Plant Inventory',
    'login.welcome': 'Bienvenido',
    'login.description': 'Ingrese sus credenciales para acceder al sistema',
    'login.email': 'Correo Electrónico',
    'login.password': 'Contraseña',
    'login.button': 'Iniciar Sesión',
    'login.invalidCredentials': 'Credenciales inválidas',
    'login.emergencyReset': 'Limpiar Sesión y Reiniciar',
    
    // Plant Selection
    'plantSelection.title': 'Seleccione una Planta',
    'plantSelection.description': 'Seleccione la planta donde realizará el inventario',
    'plantSelection.button': 'Continuar',
    'plantSelection.pleaseSelect': 'Por favor seleccione una planta',
    
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.add': 'Agregar',
    'common.close': 'Cerrar',
    'common.confirm': 'Confirmar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.complete': 'Completar',
    'common.approve': 'Aprobar',
    'common.reject': 'Rechazar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.print': 'Imprimir',
    'common.view': 'Ver',
    'common.download': 'Descargar',
    
    // Sidebar
    'sidebar.dashboard': 'Inicio',
    'sidebar.inventory': 'Inventario Mensual',
    'sidebar.reports': 'Reportes',
    'sidebar.settings': 'Configuración',
    'sidebar.documentation': 'Documentación',
    'sidebar.photosReport': 'Reporte de Fotos',
    'sidebar.databaseSetup': 'Base de Datos',
    'sidebar.connectionTest': 'Prueba de Conexión',
    'sidebar.tools': 'Herramientas',
    
    // TopBar
    'topbar.plant': 'Planta',
    'topbar.user': 'Usuario',
    'topbar.logout': 'Cerrar Sesión',
    'topbar.changePlant': 'Cambiar Planta',
    
    // Dashboard
    'dashboard.startInventory': 'Iniciar Inventario Mensual',
    'dashboard.noInventory': 'No hay un inventario activo para',
    'dashboard.startInventoryOf': 'Iniciar Inventario de',
    'dashboard.inventoryInProgress': 'Inventario en Progreso',
    'dashboard.overallProgress': 'Progreso General',
    'dashboard.completedSections': 'Secciones Completadas',
    'dashboard.pendingSections': 'Pendientes',
    'dashboard.continueInventory': 'Continuar Inventario',
    'dashboard.reviewAndApprove': 'Revisar y Aprobar',
    'dashboard.viewFeedback': 'Ver Retroalimentación',
    'dashboard.sections': 'Secciones del Inventario',
    'dashboard.period': 'Período',
    'dashboard.startTimestamp': 'Fecha y Hora de Inicio',
    'dashboard.endTimestamp': 'Fecha y Hora de Fin',
    'dashboard.checklist': 'Checklist de Secciones',
    'dashboard.inventoryProgress': 'Progreso del Inventario',
    
    // Sections
    'section.aggregates': 'Agregados',
    'section.silos': 'Silos',
    'section.additives': 'Aditivos',
    'section.diesel': 'Diesel',
    'section.products': 'Aceites y Productos',
    'section.utilities': 'Utilidades',
    'section.pettyCash': 'Petty Cash',
    
    // Section Descriptions
    'section.aggregates.desc': 'Medición de Arena, Piedra y Gravilla',
    'section.silos.desc': 'Lecturas de Cemento y Slag',
    'section.additives.desc': 'Control de Tanques y Productos Manuales',
    'section.diesel.desc': 'Control de Inventario de Diesel',
    'section.products.desc': 'Aceites, Lubricantes, Consumibles y Equipos',
    'section.utilities.desc': 'Agua y Electricidad - Lecturas de Medidores',
    'section.pettyCash.desc': 'Control de Efectivo y Recibos',
    
    // Status
    'status.pending': 'Pendiente',
    'status.inProgress': 'En Progreso',
    'status.complete': 'Completo',
    'status.completed': 'Completado',
    'status.approved': 'Aprobado',
    'status.draft': 'Borrador',
    
    // Aggregates
    'aggregates.title': 'Agregados',
    'aggregates.description': 'Medición de Arena, Piedra y Gravilla',
    'aggregates.type': 'Tipo de Material',
    'aggregates.method': 'Método de Medición',
    'aggregates.methodBox': 'Método Cajón',
    'aggregates.methodCone': 'Método Cono',
    'aggregates.arena': 'Arena',
    'aggregates.piedra': 'Piedra',
    'aggregates.gravilla': 'Gravilla',
    'aggregates.width': 'Ancho (pies)',
    'aggregates.height': 'Alto (pies)',
    'aggregates.length': 'Largo (pies)',
    'aggregates.volume': 'Volumen (yardas³)',
    'aggregates.photo': 'Foto de Evidencia',
    'aggregates.clickPhoto': 'Clic para tomar/subir foto',
    'aggregates.addAggregate': 'Agregar Agregado',
    'aggregates.saveSection': 'Guardar Agregados',
    'aggregates.photoRequired': 'La foto es obligatoria',
    
    // Silos
    'silos.title': 'Silos',
    'silos.description': 'Lecturas de Cemento y Slag',
    'silos.name': 'Nombre del Silo',
    'silos.type': 'Tipo',
    'silos.cemento': 'Cemento',
    'silos.slag': 'Slag',
    'silos.reading': 'Lectura',
    'silos.result': 'Resultado',
    'silos.photo': 'Foto de Evidencia',
    'silos.saveSection': 'Guardar Silos',
    
    // Additives
    'additives.title': 'Aditivos',
    'additives.description': 'Control de Tanques y Productos Manuales',
    'additives.tankProducts': 'Tanques',
    'additives.manualProducts': 'Productos Manuales',
    'additives.productName': 'Producto',
    'additives.brand': 'Marca',
    'additives.tankName': 'Tanque',
    'additives.reading': 'Lectura',
    'additives.readingUnit': 'Unidad de Lectura',
    'additives.volume': 'Volumen Calculado',
    'additives.gallons': 'Galones',
    'additives.quantity': 'Cantidad',
    'additives.count': 'Cantidad',
    'additives.unit': 'Unidad',
    'additives.photo': 'Foto',
    'additives.photoMeter': 'Foto del Medidor',
    'additives.addTank': 'Agregar Tanque',
    'additives.addManual': 'Agregar Producto Manual',
    'additives.saveSection': 'Guardar Aditivos',
    'additives.notes': 'Notas',
    
    // Diesel
    'diesel.title': 'Diesel',
    'diesel.description': 'Control de Inventario de Diesel',
    'diesel.tankCapacity': 'Capacidad del Tanque',
    'diesel.measurementMethod': 'Método de Medición',
    'diesel.readingInches': 'Lectura del Medidor (pulgadas)',
    'diesel.reading': 'Lectura',
    'diesel.calculatedGallons': 'Cantidad Calculada (galones)',
    'diesel.beginningInventory': 'Inventario Inicial',
    'diesel.purchases': 'Compras del Mes',
    'diesel.purchased': 'Diesel Comprado (galones)',
    'diesel.endingInventory': 'Inventario Final',
    'diesel.consumption': 'Consumo Calculado',
    'diesel.consumptionFormula': 'Fórmula: Consumo = Inventario Inicial + Compras - Inventario Final',
    'diesel.currentAmount': 'Cantidad Actual',
    'diesel.photo': 'Foto del Medidor/Tanque',
    'diesel.notes': 'Notas',
    'diesel.carriedOver': 'Inventario Arrastrado del Mes Anterior',
    'diesel.saveSection': 'Guardar Diesel',
    'diesel.saveDraft': 'Guardar Borrador',
    
    // Products
    'products.title': 'Aceites y Productos',
    'products.description': 'Aceites, Lubricantes, Consumibles y Equipos',
    'products.productName': 'Nombre del Producto',
    'products.category': 'Categoría',
    'products.measureMode': 'Método de Medición',
    'products.quantity': 'Cantidad',
    'products.photo': 'Foto',
    'products.addProduct': 'Agregar Producto',
    'products.saveSection': 'Guardar Aceites y Productos',
    'products.totalProducts': 'Total Aceites y Productos',
    'products.completed': 'Completados',
    'products.pending': 'Pendientes',
    'products.tankReading': 'Tanque con Lectura',
    'products.drum': 'Tambores',
    'products.pail': 'Pailas',
    'products.count': 'Conteo Directo',
    'products.reading': 'Lectura',
    'products.calculatedQuantity': 'Cantidad Calculada',
    'products.unitCount': 'Cantidad de Unidades',
    'products.totalVolume': 'Volumen Total',
    'products.categoryOil': 'Aceite',
    'products.categoryLubricant': 'Lubricante',
    'products.categoryConsumable': 'Consumible',
    'products.categoryEquipment': 'Equipo',
    'products.categoryOther': 'Otro',
    
    // Utilities
    'utilities.title': 'Utilidades',
    'utilities.description': 'Agua y Electricidad - Lecturas de Medidores',
    'utilities.meterName': 'Medidor',
    'utilities.meterNumber': 'Número de Medidor',
    'utilities.provider': 'Proveedor',
    'utilities.previousReading': 'Lectura Anterior',
    'utilities.currentReading': 'Lectura Actual',
    'utilities.consumption': 'Consumo Calculado',
    'utilities.consumptionOfMonth': 'Consumo del Mes',
    'utilities.photo': 'Foto del Medidor',
    'utilities.notes': 'Notas',
    'utilities.saveSection': 'Guardar Utilidades',
    'utilities.totalMeters': 'Total Medidores',
    'utilities.completed': 'Completados',
    'utilities.pending': 'Pendientes',
    'utilities.typeWaterAAA': 'Agua AAA',
    'utilities.typeWaterWell': 'Agua Pozo',
    'utilities.typeElectricity': 'Electricidad',
    'utilities.typeGas': 'Gas',
    'utilities.typeOther': 'Otro',
    'utilities.fromPreviousMonth': 'Del mes anterior',
    'utilities.initialValue': 'Valor inicial',
    'utilities.enterReading': 'Ingresa lectura...',
    'utilities.onlyFieldToFill': 'Este es el único campo que debes llenar',
    'utilities.range': 'Rango',
    
    // Petty Cash
    'pettyCash.title': 'Petty Cash',
    'pettyCash.description': 'Control de Efectivo y Recibos',
    'pettyCash.established': 'Monto Establecido',
    'pettyCash.receipts': 'Recibos',
    'pettyCash.cash': 'Efectivo',
    'pettyCash.cashOnHand': 'Efectivo en Caja',
    'pettyCash.total': 'Total',
    'pettyCash.pending': 'Pendiente',
    'pettyCash.difference': 'Diferencia',
    'pettyCash.short': 'Faltante',
    'pettyCash.over': 'Sobrante',
    'pettyCash.correct': 'Cuadra Perfecto',
    'pettyCash.photo': 'Foto de Evidencia',
    'pettyCash.photoReceipts': 'Foto de Evidencia (Recibos y Efectivo)',
    'pettyCash.notes': 'Notas / Comentarios',
    'pettyCash.saveSection': 'Guardar Petty Cash',
    'pettyCash.notEditable': 'No editable',
    'pettyCash.establishedAmount': 'Petty Cash Establecido',
    'pettyCash.compressingPhoto': 'Optimizando imagen...',
    'pettyCash.photoOptimized': 'La foto se optimizará automáticamente',
    
    // Review and Approve
    'review.title': 'Revisar y Aprobar Inventario',
    'review.description': 'Verificación de completitud y aprobación final',
    'review.status': 'Estado',
    'review.inProgress': 'En Progreso',
    'review.submitted': 'Enviado a Aprobación',
    'review.approved': 'Aprobado',
    'review.sections': 'Secciones',
    'review.completeSections': 'Secciones Completas',
    'review.criticalIssues': 'Errores Críticos',
    'review.warnings': 'Advertencias',
    'review.readOnly': 'Modo Solo Lectura',
    'review.saveDraft': 'Guardar Borrador',
    'review.submitForApproval': 'Enviar a Aprobación',
    'review.approve': 'Aprobar Inventario',
    'review.reject': 'Rechazar',
    'review.createdBy': 'Llenado por',
    'review.approvedBy': 'Aprobado por',
    'review.canSubmit': 'Puedes enviar a aprobación',
    'review.cannotSubmit': 'Corrige los errores antes de enviar',
    
    // Reports
    'reports.title': 'Reportes',
    'reports.description': 'Consulta y exportación de inventarios',
    'reports.filters': 'Filtros',
    'reports.month': 'Mes',
    'reports.year': 'Año',
    'reports.allMonths': 'Todos los meses',
    'reports.allYears': 'Todos los años',
    'reports.exportPDF': 'Exportar PDF',
    'reports.exportExcel': 'Exportar Excel',
    'reports.exportSuccess': 'Reporte exportado exitosamente',
    'reports.plant': 'Planta',
    'reports.period': 'Período',
    'reports.completedDate': 'Fecha Completado',
    'reports.aggregates': 'Agregados',
    'reports.silos': 'Silos',
    'reports.createdBy': 'Diligenciado por',
    'reports.approvedBy': 'Aprobado por',
    'reports.status': 'Estado',
    'reports.actions': 'Acciones',
    'reports.noResults': 'No hay reportes que coincidan con los filtros seleccionados',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.description': 'Gestión de plantas y configuración del sistema',
    'settings.plants': 'Gestión de Plantas',
    'settings.users': 'Gestión de Usuarios',
    'settings.general': 'Configuración General',
    'settings.plantName': 'Nombre',
    'settings.plantCode': 'Código',
    'settings.location': 'Ubicación',
    'settings.silos': 'Silos',
    'settings.pettyCash': 'Petty Cash',
    'settings.status': 'Estado',
    'settings.active': 'Activa',
    'settings.inactive': 'Inactiva',
    'settings.actions': 'Acciones',
    
    // Months
    'month.january': 'Enero',
    'month.february': 'Febrero',
    'month.march': 'Marzo',
    'month.april': 'Abril',
    'month.may': 'Mayo',
    'month.june': 'Junio',
    'month.july': 'Julio',
    'month.august': 'Agosto',
    'month.september': 'Septiembre',
    'month.october': 'Octubre',
    'month.november': 'Noviembre',
    'month.december': 'Diciembre',
    
    // Roles
    'role.superAdmin': 'Super Administrador',
    'role.admin': 'Administrador',
    'role.plantManager': 'Gerente de Planta',
  },
  en: {
    // Login
    'login.title': 'PROMIX',
    'login.subtitle': 'Plant Inventory',
    'login.welcome': 'Welcome',
    'login.description': 'Enter your credentials to access the system',
    'login.email': 'Correo electronico',
    'login.password': 'Password',
    'login.button': 'Sign In',
    'login.invalidCredentials': 'Invalid credentials',
    'login.emergencyReset': 'Clear Session and Restart',
    
    // Plant Selection
    'plantSelection.title': 'Select a Plant',
    'plantSelection.description': 'Select the plant where you will perform the inventory',
    'plantSelection.button': 'Continue',
    'plantSelection.pleaseSelect': 'Please select a plant',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.complete': 'Complete',
    'common.approve': 'Approve',
    'common.reject': 'Reject',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.print': 'Print',
    'common.view': 'View',
    'common.download': 'Download',
    
    // Sidebar
    'sidebar.dashboard': 'Home',
    'sidebar.inventory': 'Monthly Inventory',
    'sidebar.reports': 'Reports',
    'sidebar.settings': 'Settings',
    'sidebar.documentation': 'Documentation',
    'sidebar.photosReport': 'Photos Report',
    'sidebar.databaseSetup': 'Database Setup',
    'sidebar.connectionTest': 'Connection Test',
    'sidebar.tools': 'Tools',
    
    // TopBar
    'topbar.plant': 'Plant',
    'topbar.user': 'User',
    'topbar.logout': 'Logout',
    'topbar.changePlant': 'Change Plant',
    
    // Dashboard
    'dashboard.startInventory': 'Start Monthly Inventory',
    'dashboard.noInventory': 'There is no active inventory for',
    'dashboard.startInventoryOf': 'Start Inventory for',
    'dashboard.inventoryInProgress': 'Inventory in Progress',
    'dashboard.overallProgress': 'Overall Progress',
    'dashboard.completedSections': 'Completed Sections',
    'dashboard.pendingSections': 'Pending',
    'dashboard.continueInventory': 'Continue Inventory',
    'dashboard.reviewAndApprove': 'Review and Approve',
    'dashboard.viewFeedback': 'View Feedback',
    'dashboard.sections': 'Inventory Sections',
    'dashboard.period': 'Period',
    'dashboard.startTimestamp': 'Start Date and Time',
    'dashboard.endTimestamp': 'End Date and Time',
    'dashboard.checklist': 'Section Checklist',
    'dashboard.inventoryProgress': 'Inventory Progress',
    
    // Sections
    'section.aggregates': 'Aggregates',
    'section.silos': 'Silos',
    'section.additives': 'Additives',
    'section.diesel': 'Diesel',
    'section.products': 'Oils and Products',
    'section.utilities': 'Utilities',
    'section.pettyCash': 'Petty Cash',
    
    // Section Descriptions
    'section.aggregates.desc': 'Sand, Stone and Gravel Measurement',
    'section.silos.desc': 'Cement and Slag Readings',
    'section.additives.desc': 'Tank and Manual Product Control',
    'section.diesel.desc': 'Diesel Inventory Control',
    'section.products.desc': 'Oils, Lubricants, Consumables and Equipment',
    'section.utilities.desc': 'Agua y Electricidad - Lecturas de Medidores',
    'section.pettyCash.desc': 'Cash Control',
    
    // Status
    'status.pending': 'Pending',
    'status.inProgress': 'In Progress',
    'status.complete': 'Complete',
    'status.completed': 'Completed',
    'status.approved': 'Approved',
    'status.draft': 'Draft',
    
    // Aggregates
    'aggregates.title': 'Aggregates',
    'aggregates.description': 'Sand, Stone and Gravel Measurement',
    'aggregates.type': 'Material Type',
    'aggregates.method': 'Measurement Method',
    'aggregates.methodBox': 'Box Method',
    'aggregates.methodCone': 'Cone Method',
    'aggregates.arena': 'Sand',
    'aggregates.piedra': 'Stone',
    'aggregates.gravilla': 'Gravel',
    'aggregates.width': 'Width (feet)',
    'aggregates.height': 'Height (feet)',
    'aggregates.length': 'Length (feet)',
    'aggregates.volume': 'Volume (yards³)',
    'aggregates.photo': 'Evidence Photo',
    'aggregates.clickPhoto': 'Click to take/upload photo',
    'aggregates.addAggregate': 'Add Aggregate',
    'aggregates.saveSection': 'Save Aggregates',
    'aggregates.photoRequired': 'Photo is required',
    
    // Silos
    'silos.title': 'Silos',
    'silos.description': 'Cement and Slag Readings',
    'silos.name': 'Silo Name',
    'silos.type': 'Type',
    'silos.cemento': 'Cement',
    'silos.slag': 'Slag',
    'silos.reading': 'Reading',
    'silos.result': 'Result',
    'silos.photo': 'Evidence Photo',
    'silos.saveSection': 'Save Silos',
    
    // Additives
    'additives.title': 'Additives',
    'additives.description': 'Tank and Manual Product Control',
    'additives.tankProducts': 'Tanks',
    'additives.manualProducts': 'Manual Products',
    'additives.productName': 'Product',
    'additives.brand': 'Brand',
    'additives.tankName': 'Tank',
    'additives.reading': 'Reading',
    'additives.readingUnit': 'Reading Unit',
    'additives.volume': 'Calculated Volume',
    'additives.gallons': 'Gallons',
    'additives.quantity': 'Quantity',
    'additives.count': 'Count',
    'additives.unit': 'Unit',
    'additives.photo': 'Photo',
    'additives.photoMeter': 'Meter Photo',
    'additives.addTank': 'Add Tank',
    'additives.addManual': 'Add Manual Product',
    'additives.saveSection': 'Save Additives',
    'additives.notes': 'Notes',
    
    // Diesel
    'diesel.title': 'Diesel',
    'diesel.description': 'Diesel Inventory Control',
    'diesel.tankCapacity': 'Tank Capacity',
    'diesel.measurementMethod': 'Measurement Method',
    'diesel.readingInches': 'Meter Reading (inches)',
    'diesel.reading': 'Reading',
    'diesel.calculatedGallons': 'Calculated Quantity (gallons)',
    'diesel.beginningInventory': 'Beginning Inventory',
    'diesel.purchases': 'Monthly Purchases',
    'diesel.purchased': 'Diesel Purchased (gallons)',
    'diesel.endingInventory': 'Ending Inventory',
    'diesel.consumption': 'Calculated Consumption',
    'diesel.consumptionFormula': 'Formula: Consumption = Beginning Inventory + Purchases - Ending Inventory',
    'diesel.currentAmount': 'Current Amount',
    'diesel.photo': 'Meter/Tank Photo',
    'diesel.notes': 'Notes',
    'diesel.carriedOver': 'Carried Over Inventory from Previous Month',
    'diesel.saveSection': 'Save Diesel',
    'diesel.saveDraft': 'Save Draft',
    
    // Products
    'products.title': 'Oils and Products',
    'products.description': 'Oils, Lubricants, Consumables and Equipment',
    'products.productName': 'Product Name',
    'products.category': 'Category',
    'products.measureMode': 'Measurement Method',
    'products.quantity': 'Quantity',
    'products.photo': 'Photo',
    'products.addProduct': 'Add Product',
    'products.saveSection': 'Save Products',
    'products.totalProducts': 'Total Products',
    'products.completed': 'Completed',
    'products.pending': 'Pending',
    'products.tankReading': 'Tank with Reading',
    'products.drum': 'Drums',
    'products.pail': 'Pails',
    'products.count': 'Direct Count',
    'products.reading': 'Reading',
    'products.calculatedQuantity': 'Calculated Quantity',
    'products.unitCount': 'Unit Count',
    'products.totalVolume': 'Total Volume',
    'products.categoryOil': 'Oil',
    'products.categoryLubricant': 'Lubricant',
    'products.categoryConsumable': 'Consumable',
    'products.categoryEquipment': 'Equipment',
    'products.categoryOther': 'Other',
    
    // Utilities
    'utilities.title': 'Utilidades',
    'utilities.description': 'Agua y Electricidad - Lecturas de Medidores',
    'utilities.meterName': 'Medidor',
    'utilities.meterNumber': 'Número de Medidor',
    'utilities.provider': 'Proveedor',
    'utilities.previousReading': 'Lectura Anterior',
    'utilities.currentReading': 'Lectura Actual',
    'utilities.consumption': 'Consumo Calculado',
    'utilities.consumptionOfMonth': 'Consumo del Mes',
    'utilities.photo': 'Foto del Medidor',
    'utilities.notes': 'Notas',
    'utilities.saveSection': 'Guardar Utilidades',
    'utilities.totalMeters': 'Total Medidores',
    'utilities.completed': 'Completados',
    'utilities.pending': 'Pendientes',
    'utilities.typeWaterAAA': 'Agua AAA',
    'utilities.typeWaterWell': 'Agua Pozo',
    'utilities.typeElectricity': 'Electricidad',
    'utilities.typeGas': 'Gas',
    'utilities.typeOther': 'Otro',
    'utilities.fromPreviousMonth': 'Del mes anterior',
    'utilities.initialValue': 'Valor inicial',
    'utilities.enterReading': 'Ingresa lectura...',
    'utilities.onlyFieldToFill': 'Este es el único campo que debes llenar',
    'utilities.range': 'Rango',
    
    // Petty Cash
    'pettyCash.title': 'Petty Cash',
    'pettyCash.description': 'Cash Control',
    'pettyCash.established': 'Established Amount',
    'pettyCash.receipts': 'Receipts',
    'pettyCash.cash': 'Cash',
    'pettyCash.cashOnHand': 'Cash on Hand',
    'pettyCash.total': 'Total',
    'pettyCash.pending': 'Pending',
    'pettyCash.difference': 'Difference',
    'pettyCash.short': 'Short',
    'pettyCash.over': 'Over',
    'pettyCash.correct': 'Balances',
    'pettyCash.photo': 'Evidence Photo',
    'pettyCash.photoReceipts': 'Evidence Photo (Receipts and Cash)',
    'pettyCash.notes': 'Notes / Comments',
    'pettyCash.saveSection': 'Save Petty Cash',
    'pettyCash.notEditable': 'Not Editable',
    'pettyCash.establishedAmount': 'Established Petty Cash',
    'pettyCash.compressingPhoto': 'Optimizing image...',
    'pettyCash.photoOptimized': 'The photo will be automatically optimized',
    
    // Review and Approve
    'review.title': 'Final Review',
    'review.description': 'Review all data before approving and syncing',
    'review.plant': 'Plant',
    'review.period': 'Period',
    'review.createdBy': 'Completed by',
    'review.approvedBy': 'Approved by',
    'review.pendingApproval': 'Pending Approval',
    'review.toApprove': 'To approve',
    'review.sectionsummary': 'Summary by Section',
    'review.incompleteSections': 'incomplete section(s). Complete all sections before approving.',
    'review.approveButton': 'Approve and Sync',
    'review.successMessage': 'Inventory approved and synced successfully!',
    
    // Reports
    'reports.title': 'Reports',
    'reports.description': 'Inventory lookup and export',
    'reports.filters': 'Filters',
    'reports.month': 'Month',
    'reports.year': 'Year',
    'reports.allMonths': 'All months',
    'reports.allYears': 'All years',
    'reports.exportPDF': 'Export PDF',
    'reports.exportExcel': 'Export Excel',
    'reports.exportSuccess': 'Report exported successfully',
    'reports.plant': 'Plant',
    'reports.period': 'Period',
    'reports.completedDate': 'Completed Date',
    'reports.aggregates': 'Aggregates',
    'reports.silos': 'Silos',
    'reports.createdBy': 'Completed by',
    'reports.approvedBy': 'Approved by',
    'reports.status': 'Status',
    'reports.actions': 'Actions',
    'reports.noResults': 'No reports match the selected filters',
    
    // Settings
    'settings.title': 'Settings',
    'settings.description': 'Plant management and system configuration',
    'settings.plants': 'Plant Management',
    'settings.users': 'User Management',
    'settings.general': 'General Settings',
    'settings.plantName': 'Name',
    'settings.plantCode': 'Code',
    'settings.location': 'Location',
    'settings.silos': 'Silos',
    'settings.pettyCash': 'Petty Cash',
    'settings.status': 'Status',
    'settings.active': 'Active',
    'settings.inactive': 'Inactive',
    'settings.actions': 'Actions',
    
    // Months
    'month.january': 'January',
    'month.february': 'February',
    'month.march': 'March',
    'month.april': 'April',
    'month.may': 'May',
    'month.june': 'June',
    'month.july': 'July',
    'month.august': 'August',
    'month.september': 'September',
    'month.october': 'October',
    'month.november': 'November',
    'month.december': 'December',
    
    // Roles
    'role.superAdmin': 'Super Administrator',
    'role.admin': 'Administrator',
    'role.plantManager': 'Plant Manager',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
