ALTER TABLE public.plant_additives_config
  ADD COLUMN IF NOT EXISTS additive_type TEXT NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS brand TEXT,
  ADD COLUMN IF NOT EXISTS uom TEXT,
  ADD COLUMN IF NOT EXISTS requires_photo BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tank_name TEXT,
  ADD COLUMN IF NOT EXISTS reading_uom TEXT,
  ADD COLUMN IF NOT EXISTS conversion_table JSONB;

